### PR TITLE
#2 - Privately Scoped Functions

### PR DESCRIPTION
**Pull request by ghost**
This PR addresses the need to privately scope functions through the `ase` library, via #2 .

### CODE REVIEW

**Comment by ARolek** [comment]
@francismakes did you run this code yet to make sure that it still works?

**Comment by ghost** [comment]
@ARolek In the lieu of the test suite, I tested it locally and it works on my machine without error. All of the changes only affected its relative local file; on the whole, it did not affect `ase.go` which used the respective `Read` function from the other files.

**Comment by ARolek** [comment]
@francismakes that's what I was referring to. If you had tested it locally. ;-)

**Comment by ghost** [comment]
@ARolek Awesome!

**Pull request merged**
