### PR TITLE
Unit Tests

### PR DESCRIPTION
**Pull request by ghost**
This PR is an attempt to write the first set of unit tests for the ase library.

Notes: 
- This is still a work-in-progress since there are still some unit tests that require more discussion (see questions below)
- the `ase_test.go` asserts that the values decoded from `test.ase` are all correct and heavily models from the example code given in the `readme`.
- the `block_test.go`, `color_test.go` and `group_test.go` only test the default values from the defined struct. The unit tests are still pending for each of their respective `#Read` functions.

Questions:
- Is it overkill to test the default values / types for each struct in the `ase` library? If it is, I can push commits that removes those assertions.
- I am having trouble finding "just enough" sample input for `block`, `color` and `group` to test that `Read` works. Since the expected input is expecting a file of the `bytes.NewReader` type, how can we best mock the input that loads a binary file but with just the necessary input to test the function?
- From the first question, each `Read` function expects a file to be loaded. Is there a way to mock a file being loaded instead with just a slice literal composed of byte elements?
- Would anyone from the community please provide a code review before merging? Much appreciated! :smiley:

### CODE REVIEW

**Comment by ghost** [comment]
Also: an obvious refactor from these units is to write a helper method that passes in the testing context, expected value and actual value for each assertion. I was looking at [testify](https://github.com/stretchr/testify) and their assertion methods but am looking to only extract their `assert.Equal` method and fit it into the codebase versus requiring the entire package. Thoughts appreciated on this @ARolek !

**Comment by ARolek** [comment]
@francismakes I think it makes the most sense to write tests at the Decode level, and inspect the results. This would be more of an "integration test" where the file we pass to Decode has all the various situations that could arise and we confirm the output is what's desired. Does this make sense?

**Comment by ghost** [comment]
@ARolek That makes sense. To incorporate your direction, I can revise the commits to only test the Decode functionality within `ase.go` and remove the other units regarding the `Read` methods. Do you think that would be best moving forward? That way when Encode is integrated, whatever testing facilities we use will only be concerned with whether or not the encoding / decoding works.

**Comment by ARolek** [comment]
@francismakes yep, that's the way I would test it. Rather than test every function, let's test input / output. That ASE file I sent you should cover all the various requirements. We could potentially test the Encode by trying to match the sample ase file and then running it through Decode to make sure the output is what we want as well.

**Comment by ghost** [comment]
@ARolek Last four commits remove irrelevant unit tests, include `samples/test.ase` for the primary test file and ensures that all units for `ase#Decode()` pass.

**Comment by ARolek** [comment]
@francismakes I might be missing something here, but it appears you're only checking one color. I believe there are 4 independent colors, and a color group that has 3 colors in the test.ase file. Am I missing something?

**Comment by ghost** [comment]
@ARolek aha! you are right. I will update the code to include those test
cases. Thank you for the check.

**Comment by ghost** [comment]
Quick update: checking the length of `ase.Colors` from the test file, there are actually 8 colors to test from. Will be writing the proper units to ensure that each of their properties are read as expected.

**Comment by ghost** [comment]
@ARolek Updated the unit test to check every color within the sample `ase` via the `range` operator checking against a slice of expected `Color`s.

Questions:
1. When you mentioned four independent colors earlier, did you mean independent colors in types of colors or the total quantity present in `ase.Colors`? I found a quantity of eight from the unit tests.
2. When I tested the length of `ase.Groups` there were none present. Was there supposed to be a color group defined elsewhere that I missed when running tests?

**Comment by ARolek** [comment]
@francismakes I can double check, but from the email when I sent the test.ase file:

_Attached is a test.ase file you can use for the unit tests. I has a blend of individual colors and then a color group with a few colors in it. It would probably make sense to confirm we can decode and encode into this format._

**Individual colors**
- RGB: R: 255, G: 255, B: 255
- Grayscale: Not quite sure what these values will come out as
- CMYK: C: 0, M: 100, Y: 0, K:0
- PANTONE: PANTONE P 1-8 C

**Color Group**
- A Color Group:
- Red: R: 255, G: 0, B: 0
- Green: R: 0, G: 255, B: 0
- Blue: R: 0, G: 0, B: 255

The names before the colon (:) are what the colors / groups are named. That's strange that you're getting 8 colors out of the file, and not 7. There should be 4 colors (support for each color space) and then a color group with 3 colors (Red, Green, Blue). 

Can you convert the output to JSON and post the payload?

**Comment by ghost** [comment]
@ARolek As requested, JSON payload of `ase.Colors` read from `samples/test.ase`

``` json
[
    {
        "NameLen": 4,
        "Name": "RGB",
        "Model": "RGB",
        "Values": [
            1,
            1,
            1
        ],
        "Type": "Normal"
    },
    {
        "NameLen": 10,
        "Name": "Grayscale",
        "Model": "CMYK",
        "Values": [
            0,
            0,
            0,
            0.47
        ],
        "Type": "Spot"
    },
    {
        "NameLen": 5,
        "Name": "cmyk",
        "Model": "CMYK",
        "Values": [
            0,
            1,
            0,
            0
        ],
        "Type": "Spot"
    },
    {
        "NameLen": 4,
        "Name": "LAB",
        "Model": "RGB",
        "Values": [
            0,
            0.6063648,
            0.524658
        ],
        "Type": "Global"
    },
    {
        "NameLen": 16,
        "Name": "PANTONE P 1-8 C",
        "Model": "LAB",
        "Values": [
            0.9137255,
            -5,
            94
        ],
        "Type": "Spot"
    },
    {
        "NameLen": 4,
        "Name": "Red",
        "Model": "RGB",
        "Values": [
            1,
            0,
            0
        ],
        "Type": "Global"
    },
    {
        "NameLen": 6,
        "Name": "Green",
        "Model": "RGB",
        "Values": [
            0,
            1,
            0
        ],
        "Type": "Global"
    },
    {
        "NameLen": 5,
        "Name": "Blue",
        "Model": "RGB",
        "Values": [
            0,
            0,
            1
        ],
        "Type": "Global"
    }
]

```

I understand what you mean now that you break it up that way: four independent colors (RGB, Grayscale, YMCK, Pantone), but what makes it quantity 8 is the 3rd entry shown above, whose name is `LAB` but model is `RGB`:

``` json
    {
        "NameLen": 4,
        "Name": "LAB",
        "Model": "RGB",
        "Values": [
            0,
            0.6063648,
            0.524658
        ],
        "Type": "Global"
    }
```

Questions:
1. Was it intentional to have this extra entry?
2. If it was intentional should we keep it and perhaps place a special note on it?
3. It it was not should we remove it from the test file?

**Comment by ghost** [comment]
Observation: each element in the above payload have either three or four integer elements for its respective `Values`. Unit tests do not take into account the possible fourth element, so I'll push a commit adding those checks.

**Comment by ARolek** [comment]
@francismakes I just checked the actual swatch, and I does actually have 8 entries. Here's the modified details:

Individual colors
- RGB: R: 255, G: 255, B: 255
- Grayscale: C: 0, M: 0, Y: 0, K: 0.47 (I will check if this profile should be in CMYK format)
- CMYK: C: 0, M: 100, Y: 0, K:0
- LAB: L: 57, a: -40, b: 0 (I will need to check why the colorspace is RGB in your output)
- PANTONE: PANTONE P 1-8 C

A Color Group:
- Red: R: 255, G: 0, B: 0
- Green: R: 0, G: 255, B: 0
- Blue: R: 0, G: 0, B: 255

It looks like two of the colors did not get written correctly when I exported the swatch from the Illustrator: Lab and Grayscale. It would be ideal for the test swatch to have these color spaces correct on decoding to confirm the test. I will look into this.

Correct observation about the color consisting of either 3 or 4 _float32_ values. It depends on the colorspace. 

Also note that ASE.Decode() accepts a second param, a bool, which will determine if the colors in a group should be nested the ASE.Groups part of the struct, or stored in the Color slice of the struct. It might be helpful when reviewing the output to pass in `false` for this param so you can see the group info.

**Comment by ghost** [comment]
Note: the output definitely changes when running `ase.Decode(filePath, true)`.

``` json
{
    "Signature": "ASEF",
    "Version": [1, 0],
    "NumBlocks": [10],
    "Colors": [{
        "NameLen": 4,
        "Name": "RGB",
        "Model": "RGB",
        "Values": [1, 1, 1],
        "Type": "Normal"
    }, {
        "NameLen": 10,
        "Name": "Grayscale",
        "Model": "CMYK",
        "Values": [0, 0, 0, 0.47],
        "Type": "Spot"
    }, {
        "NameLen": 5,
        "Name": "cmyk",
        "Model": "CMYK",
        "Values": [0, 1, 0, 0],
        "Type": "Spot"
    }, {
        "NameLen": 4,
        "Name": "LAB",
        "Model": "RGB",
        "Values": [0, 0.6063648, 0.524658],
        "Type": "Global"
    }, {
        "NameLen": 16,
        "Name": "PANTONE P 1-8 C",
        "Model": "LAB",
        "Values": [0.9137255, -5, 94],
        "Type": "Spot"
    }],
    "Groups": {
        "A Color Group": [{
            "NameLen": 4,
            "Name": "Red",
            "Model": "RGB",
            "Values": [1, 0, 0],
            "Type": "Global"
        }, {
            "NameLen": 6,
            "Name": "Green",
            "Model": "RGB",
            "Values": [0, 1, 0],
            "Type": "Global"
        }, {
            "NameLen": 5,
            "Name": "Blue",
            "Model": "RGB",
            "Values": [0, 0, 1],
            "Type": "Global"
        }]
    }
}
```

Will be pushing up a commit that includes this case.

**Pull request closed without merging**
